### ISSUE TITLE
训练集正确率为什么远低于测试集？

### ISSUE THREAD

**Issue by liujiawen-jpg** [yushuowiki/ALTER#1]
您好，我想询问一下，为什么在我训练您的模型的训练集正确率会低于测试集呢？训练集正确率往往在百分之55，而测试集却能达到75，74？这是否是您的模型欠拟合呢还是计算正确率的方法您写错了？

**Comment by liujiawen-jpg** [comment]
是我对这方面没有了解出言不逊了，将mixup调整成false，训练集正确率即恢复正常

**Comment by Cindy10227** [comment]
您好！我想请教一下代码中的abide.npy在哪里获取呢？

**Comment by liujiawen-jpg** [comment]
这篇论文的代码基于BraninNetwork Transformer, GitHub搜索这个项目，里面的数据集就是你要的abide.npy

**Comment by Dawn-dd** [comment]
您好，我想问一下论文中的另外一个数据集ADNI您是怎么实现的呢？
